#!/bin/sh
PWD=`pwd`
export ROOT_FS=$PWD/../rootfs-x86_64/
export ISO_FS=$PWD/iso9660/
export ISO_IMAGE=$PWD/stali.iso
cp $ROOT_FS/boot/vmlinuz $ISO_FS/isolinux/vmlinuz
(cd $ROOT_FS && find . -type l -printf '%p %Y\n' | sed -n 's/ [LN]$//p' | xargs -rL1 rm -f)
(cd $ROOT_FS && find . | grep -v \.\/\.git | cpio --owner root:root --quiet -o -H newc | gzip -9 >${ISO_FS}/isolinux/initrd.img)
rm -f $ISO_IMAGE
genisoimage -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -l -input-charset default -V stali -A "stali" -o $ISO_IMAGE $ISO_FS
